# Generated by Django 5.1.3 on 2024-11-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_name_bleachcharacter_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bleachcharacter',
            old_name='nombre',
            new_name='name',
        ),
    ]
